version: '3.7'

services:
################################################################################
# web app server                                                               #
################################################################################
  webapp:
    container_name: webapp
    build:
      context: webapp
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on: 
      - webapi
################################################################################
# Rest API Server                                                              #
################################################################################
  webapi:
    build:
      context: webapi
      dockerfile: Dockerfile
    ports:
      - "8000:80"
