version: '3.7'

services:
################################################################################
# webb app server                                                              #
################################################################################
  webapp:
    container_name: webapp
    build:
      context: webapp
      dockerfile: Dockerfile
    expose:
      - ${REACT_APP_PORT}
    volumes:
      - '.:/webapp'
      - '/webapp/node_modules'
    environment:
      - NODE_ENV=development
    ports:
      - '${REACT_APP_PORT}:${REACT_APP_PORT}'
